name: PortageClusterUtils test suite

on: [push]

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Run tests
      run: >
        source SETUP.bash
        && cd tests
        && ./run-all-tests.sh
